config/routes.rb
Rails.application.routes.draw do
  resources :people

  get 'query_db/:numbeDocument', to: 'people#query_db'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
require 'net/http'
require 'uri'
require 'nokogiri'
require 'json'

class Person < ApplicationRecord

    def self.splash(dni)
        init = Time.now.strftime('%s%L').to_i
  
        script = "
                  function main(splash, args)
                    assert(splash:go(args.url))
                    assert(splash:wait(0.5))
                    
                    local form = splash:select('#buscar-por-dni')
                    local values = {
                      dni = #{dni}
                    }
                    assert(form:fill(values))
                    assert(form:submit())
  
                    while not splash:select('table') do
                      splash:wait(0.1)
                    end
                  
                    return {
                      html = splash:html(),
                    }
                  end
        "
        
        uri = URI.parse("http://localhost:8050/execute?") 
  
        request = Net::HTTP::Post.new(uri)
        request.content_type = "application/json"
        request.body = JSON.dump({
          "url" => 'https://eldni.com/pe/buscar-por-dni',
          "wait" => 1,
          "lua_source" => script,
        })
  
        req_options = {
          use_ssl: uri.scheme == "https",
        }
  
        response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
          http.request(request)
        end
    
        page    = Nokogiri::HTML(response.body)
        items   = page.css('table tbody tr td')

        diff    = Time.now.strftime('%s%L').to_i - init
  
        data  = {
            numbeDocument:    items[0].text,
            name:             items[1].text,
            paternalLastName: items[2].text,
            maternalLastName: items[3].text,
            diff:             "#{diff} ms"   
        }
  
        return data

    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end


  def query_db 
    init = Time.now.strftime('%s%L').to_i
    
    person = Person.where(:numbeDocument => params[:numbeDocument]).first
    #person = Person.where(:numbeDocument => '41250411').first
    
    if person !=  nil
      
      diff    = Time.now.strftime('%s%L').to_i - init

      render json: {
        message:  "Resultados encontrados en BD",
        data:     person,
        diff:     "#{diff} ms"
      }

    else
      resul = Person.splash(params[:numbeDocument])

      if !resul.nil?
        @person = Person.create(
          numbeDocument:    resul[:numbeDocument],
          name:             resul[:name],
          paternalLastName: resul[:paternalLastName],         
          maternalLastName: resul[:maternalLastName]
        )
      end

      render json: {
        message: "Búsqueda con splash y guardado en base de datos",
        data: resul, 
        diff: resul[:diff]
      }

    end
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:numbeDocument, :name, :paternalLastName, :maternalLastName)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QueryDocuments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numbeDocument %>
    <%= form.text_field :numbeDocument %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :paternalLastName %>
    <%= form.text_field :paternalLastName %>
  </div>

  <div class="field">
    <%= form.label :maternalLastName %>
    <%= form.text_field :maternalLastName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Numbedocument</th>
      <th>Name</th>
      <th>Paternallastname</th>
      <th>Maternallastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.numbeDocument %></td>
        <td><%= person.name %></td>
        <td><%= person.paternalLastName %></td>
        <td><%= person.maternalLastName %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numbedocument:</strong>
  <%= @person.numbeDocument %>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Paternallastname:</strong>
  <%= @person.paternalLastName %>
</p>

<p>
  <strong>Maternallastname:</strong>
  <%= @person.maternalLastName %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>